services:
  tz:
    container_name: tz
    build: .
    ports:
      - 8001:8001
    command: bash -c "alembic upgrade head && gunicorn -b 0.0.0.0:8001 -k uvicorn.workers.UvicornWorker src.main:app"
    environment:
      APP_NAME: "tz"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:


